export const CONFIG = Object.freeze({
  text: {
    openingRecipient: 'For Ivy',
    openingNote: 'Something grew here for you.',
    beginLabel: 'Tap to begin',
    birthdayHeading: 'Happy Birthday, Ivy 🌻',
    birthdayMessage: 'I hope this year gives you more reasons to smile.',
    signature: '— Elvin',
  },
  palette: {
    name: 'Golden Hour',
    petalLight: '#ffe99a',
    petalMain: '#ffc536',
    petalShadow: '#e98a17',
    centerDeep: '#21140c',
    centerMid: '#613313',
    centerWarm: '#a65c1c',
    centerHoney: '#f0a728',
    stem: '#244c36',
    leaf: '#47704e',
    leafLight: '#8b9d69',
    sepal: '#355c37',
    wrapIvory: '#f2dfb6',
    wrapSage: '#9eaa81',
    ribbon: '#e9e0bd',
    filler: '#fff4c9',
    sparkle: '#ffe58a',
  },
  timeline: {
    bloomEnd: 14.2,
    messageAt: 12.1,
    reducedMotionBloomEnd: 1.2,
  },
  flower: {
    mobileCount: 10,
    desktopCount: 15,
    heroFlowers: 3,
    rotationSecondsMobile: 45,
    rotationSecondsDesktop: 38,
  },
  quality: {
    mobileLow: { discs: 250, petalSamples: 16, leaves: 12, filler: 260, wrapping: 900, dust: 90 },
    mobileHigh: { discs: 470, petalSamples: 24, leaves: 16, filler: 430, wrapping: 1500, dust: 150 },
    desktop: { discs: 760, petalSamples: 29, leaves: 22, filler: 680, wrapping: 2400, dust: 260 },
  },
});
